# -*- encoding: utf-8 -*-
#
=begin
#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version:

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

$:.push File.expand_path("../lib", __FILE__)
require "qwil_api/version"

Gem::Specification.new do |s|
  s.name        = "qwil_api"
  s.version     = QwilAPI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Paul Tiplady"]
  s.email       = ["paul@qwil.co"]
  s.homepage    = "https://github.com/qwil/ruby-api-client"
  s.summary     = " Ruby Gem"
  s.description = "API client for the Qwil API."
  s.license     = "MIT"

  s.add_runtime_dependency 'typhoeus'
  s.add_runtime_dependency 'json'

  s.add_development_dependency 'rspec'
  s.add_development_dependency 'vcr'
  s.add_development_dependency 'webmock'
  s.add_development_dependency 'autotest'
  s.add_development_dependency 'autotest-rails-pure'
  s.add_development_dependency 'autotest-growl'
  s.add_development_dependency 'autotest-fsevent'

  s.files         = `find *`.split("\n").uniq.sort.select{|f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
