=begin
#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for QwilAPI::ManagersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ManagersApi' do
  before do
    # run before each test
    @instance = QwilAPI::ManagersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ManagersApi' do
    it 'should create an instact of ManagersApi' do
      expect(@instance).to be_instance_of(QwilAPI::ManagersApi)
    end
  end

  # unit tests for manager_platform_create
  # Endpoint for the Platforms owned by a Manager
  # Endpoint for the Platforms owned by a Manager.
  # @param manager_pk 
  # @param name 
  # @param company_information 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :contact_information 
  # @option opts [String] :currency The ISO 4217 currency code for which all payments for this Platform are handled. Note: Immutable after Platform is created.
  # @option opts [String] :payment_schedule The frequency of contractor rebates on this platform.
  # @option opts [Date] :payment_date The date that the first payment is due for the platform&#39;s pay cycle.
  # @option opts [String] :accounts The accounts configured for billing on this Platform.
  # @option opts [String] :default_account The account to use for billing purposes.
  # @return [ManagerPlatformSerializer]
  describe 'manager_platform_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for manager_platform_list
  # Endpoint for the Platforms owned by a Manager
  # Endpoint for the Platforms owned by a Manager.
  # @param manager_pk 
  # @param [Hash] opts the optional parameters
  # @return [Array<ManagerPlatformSerializer>]
  describe 'manager_platform_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for manager_retrieve
  # Endpoint for Manager objects, which describe entities that can create and manage Platforms
  # Endpoint for Manager objects, which describe entities that can create and manage Platforms.
  # @param pk 
  # @param [Hash] opts the optional parameters
  # @return [ManagerSerializer]
  describe 'manager_retrieve test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
